import localFont from "next/font/local";
// import "../styles/globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import LoginForm from '../components/LoginForm';

export default function Home() {
  return (
    <div className="container">
      <LoginForm />
    </div>
  );
}


